"""
This code was generated by Qingyu Feng
on Dec 20, 2014

The goal of this program was to test the sensitivity of
fuzzy logic system to the variations of input criteria.

The method used for sensitivity analysis is called one at
a time. This code aimed at evaluate the global sensitivity of
each variable.

This code stores the values of each variable

"""

from numpy import arange, zeros, ones

# Parameter values


# depth (cm)
depth_min = 15.0
depth_max = 40.0
depth_mp = 27.5


# slope (%)
slope_min = 6.0
slope_max = 18.0
slope_mp = 12.0

# salinity:
salinity_min = 5.0
salinity_max = 14.5
salinity_mp = 9.75

# ph
ph_min = 3.7
ph_mpl = 6.0
ph_mpr = 7.6
ph_max = 8.0
ph_lm = 4.85
ph_rm = 7.8

# Growing season precipitation
prcp_grow_min = 200.0
prcp_grow_max = 600.0
prcp_grow_mp = 400.0

"""
Input series were generated for each input variables.
"""
depth_input = arange(depth_min*0.6, depth_max*1.6, (depth_max*1.6 - depth_min*0.6)/10)
slope_input = arange(slope_min*0.6, slope_max*1.6, (slope_max*1.6 - slope_min*0.6)/10)
salinity_input = arange(salinity_min*0.6, salinity_max*1.6, (salinity_max*1.6 - salinity_min*0.6)/10)
#ph_input = arange(0, 15, 0.5)
ph_input = arange(ph_min*0.6, ph_max*1.6, (ph_max*1.6 - ph_min*0.6)/10)

prcp_grow_input = arange(prcp_grow_min*0.6, prcp_grow_max*1.6, (prcp_grow_max*1.6 - prcp_grow_min*0.6)/10)

"""
This function combines the examples and generate the example land plots
that have combination ofa each variables values.
"""

# Scale is used to change the values of input criteria
scale_change = arange(0.8, 1.3, 0.1)
scale_change_ph = arange(0.9, 1.15, 0.05)

scale_unchange = ones(5)
print scale_change
print scale_unchange

# Typical values of defuzzification
hs_com = 0.90
gs_com = 0.64
ms_com = 0.48
ps_com = 0.32
ns_com = 0.08
